# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flowmi < Formula
  desc "Flowmi CLI — notes, auth, and more from your terminal"
  homepage "https://github.com/flowmi-ai/flowmi"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flowmi-ai/flowmi/releases/download/v0.3.0/flowmi_0.3.0_darwin_amd64.tar.gz"
      sha256 "e8582ef5a36a19f4ae38eecbb153b8c6956645868978880fd8593e0070cc013e"

      define_method(:install) do
        bin.install "flowmi"
        bin.install_symlink "flowmi" => "fm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flowmi-ai/flowmi/releases/download/v0.3.0/flowmi_0.3.0_darwin_arm64.tar.gz"
      sha256 "49ab5d68d3584f9c650a95ee6bef6eca043c110f12241b82957e18afd8054340"

      define_method(:install) do
        bin.install "flowmi"
        bin.install_symlink "flowmi" => "fm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flowmi-ai/flowmi/releases/download/v0.3.0/flowmi_0.3.0_linux_amd64.tar.gz"
      sha256 "cb2b199b0d007b9ace6a1f8c6e298c81241e6b1f33e22b153a0337aa2d8968b7"
      define_method(:install) do
        bin.install "flowmi"
        bin.install_symlink "flowmi" => "fm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flowmi-ai/flowmi/releases/download/v0.3.0/flowmi_0.3.0_linux_arm64.tar.gz"
      sha256 "fa9c6540210c27c591e72b525fa3c641d6dcafa3fb18c604e7a89728c25bdcaf"
      define_method(:install) do
        bin.install "flowmi"
        bin.install_symlink "flowmi" => "fm"
      end
    end
  end
end
